spring:
  data:
    mongodb:
      username: manuel
      password: manuel
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.celyng.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.celyng.ecommerce.notification.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: manuel
    password: manuel
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040